update jobs SET FK_customer_Id = '1' where cust_Name = 'Ace Tooling';
update jobs SET FK_customer_Id = '2' where cust_Name = 'Advance Mould Engg';
update jobs SET FK_customer_Id = '3' where cust_Name = 'Advantage Eng';
update jobs SET FK_customer_Id = '4' where cust_Name = 'AFK Engineering';
update jobs SET FK_customer_Id = '5' where cust_Name = 'Alan';
update jobs SET FK_customer_Id = '6' where cust_Name = 'Alloy Race Components';
update jobs SET FK_customer_Id = '7' where cust_Name = 'Alltek';
update jobs SET FK_customer_Id = '8' where cust_Name = 'Aortech';
update jobs SET FK_customer_Id = '9' where cust_Name = 'APE';
update jobs SET FK_customer_Id = '10' where cust_Name = 'Apex Tooling';
update jobs SET FK_customer_Id = '11' where cust_Name = 'Arrk';
update jobs SET FK_customer_Id = '12' where cust_Name = 'Atech';
update jobs SET FK_customer_Id = '13' where cust_Name = 'Atlas Tooling';
update jobs SET FK_customer_Id = '14' where cust_Name = 'Aust.Power Steering';
update jobs SET FK_customer_Id = '15' where cust_Name = 'Aztech Tooling';
update jobs SET FK_customer_Id = '16' where cust_Name = 'B&M Messer';
update jobs SET FK_customer_Id = '17' where cust_Name = 'B&S Engineering';
update jobs SET FK_customer_Id = '18' where cust_Name = 'Bainbridge';
update jobs SET FK_customer_Id = '19' where cust_Name = 'Bayline Tooling';
update jobs SET FK_customer_Id = '20' where cust_Name = 'Bill messer';
update jobs SET FK_customer_Id = '21' where cust_Name = 'BIS';
update jobs SET FK_customer_Id = '22' where cust_Name = 'Borland Racing';
update jobs SET FK_customer_Id = '23' where cust_Name = 'Bosch';
update jobs SET FK_customer_Id = '24' where cust_Name = 'Bosch(A.Wilson)';
update jobs SET FK_customer_Id = '25' where cust_Name = 'Boss Rubber';
update jobs SET FK_customer_Id = '26' where cust_Name = 'Bradlor';
update jobs SET FK_customer_Id = '27' where cust_Name = 'Brenco';
update jobs SET FK_customer_Id = '28' where cust_Name = 'BSR Engg';
update jobs SET FK_customer_Id = '29' where cust_Name = 'Camec';
update jobs SET FK_customer_Id = '30' where cust_Name = 'CNC Specialist';
update jobs SET FK_customer_Id = '31' where cust_Name = 'Columbia Die Sinking';
update jobs SET FK_customer_Id = '32' where cust_Name = 'Continental';
update jobs SET FK_customer_Id = '33' where cust_Name = 'CP Maintenance';
update jobs SET FK_customer_Id = '34' where cust_Name = 'Creation Plastics';
update jobs SET FK_customer_Id = '35' where cust_Name = 'Dair Industries';
update jobs SET FK_customer_Id = '36' where cust_Name = 'Derek';
update jobs SET FK_customer_Id = '37' where cust_Name = 'Dotmar';
update jobs SET FK_customer_Id = '38' where cust_Name = 'Dunbier';
update jobs SET FK_customer_Id = '39' where cust_Name = 'Ebtech';
update jobs SET FK_customer_Id = '40' where cust_Name = 'Elgar';
update jobs SET FK_customer_Id = '41' where cust_Name = 'Emona Tooling';
update jobs SET FK_customer_Id = '42' where cust_Name = 'Excaliber Industries';
update jobs SET FK_customer_Id = '43' where cust_Name = 'Exim';
update jobs SET FK_customer_Id = '44' where cust_Name = 'Farley Productions';
update jobs SET FK_customer_Id = '45' where cust_Name = 'Fasco';
update jobs SET FK_customer_Id = '46' where cust_Name = 'FBSystems';
update jobs SET FK_customer_Id = '47' where cust_Name = 'Forge Cast';
update jobs SET FK_customer_Id = '48' where cust_Name = 'Four Star Tooling';
update jobs SET FK_customer_Id = '49' where cust_Name = 'G.Creek';
update jobs SET FK_customer_Id = '50' where cust_Name = 'G.T.M.Engg';
update jobs SET FK_customer_Id = '51' where cust_Name = 'H.M.Precision';
update jobs SET FK_customer_Id = '52' where cust_Name = 'H.Machinery';
update jobs SET FK_customer_Id = '53' where cust_Name = 'Hales';
update jobs SET FK_customer_Id = '54' where cust_Name = 'Hardman Bros';
update jobs SET FK_customer_Id = '55' where cust_Name = 'Hella';
update jobs SET FK_customer_Id = '56' where cust_Name = 'Hook Plastics';
update jobs SET FK_customer_Id = '57' where cust_Name = 'HPT';
update jobs SET FK_customer_Id = '58' where cust_Name = 'Indo-Austech';
update jobs SET FK_customer_Id = '59' where cust_Name = 'Innovonics';
update jobs SET FK_customer_Id = '60' where cust_Name = 'Invetech';
update jobs SET FK_customer_Id = '61' where cust_Name = 'ITW';
update jobs SET FK_customer_Id = '62' where cust_Name = 'JM Casteneda';
update jobs SET FK_customer_Id = '63' where cust_Name = 'Jodek';
update jobs SET FK_customer_Id = '64' where cust_Name = 'Johnson controls';
update jobs SET FK_customer_Id = '65' where cust_Name = 'KLR Engineering';
update jobs SET FK_customer_Id = '66' where cust_Name = 'Koppa Engg';
update jobs SET FK_customer_Id = '67' where cust_Name = 'L&B';
update jobs SET FK_customer_Id = '68' where cust_Name = 'L&B Engineering';
update jobs SET FK_customer_Id = '69' where cust_Name = 'Lightening Laser';
update jobs SET FK_customer_Id = '70' where cust_Name = 'Lockers';
update jobs SET FK_customer_Id = '71' where cust_Name = 'Mack Bros';
update jobs SET FK_customer_Id = '72' where cust_Name = 'Mark Engg';
update jobs SET FK_customer_Id = '73' where cust_Name = 'Matrix';
update jobs SET FK_customer_Id = '74' where cust_Name = 'Mauer';
update jobs SET FK_customer_Id = '75' where cust_Name = 'Metal Form';
update jobs SET FK_customer_Id = '76' where cust_Name = 'Metro Tool & Die';
update jobs SET FK_customer_Id = '77' where cust_Name = 'Metronom';
update jobs SET FK_customer_Id = '78' where cust_Name = 'MoldSkil';
update jobs SET FK_customer_Id = '79' where cust_Name = 'Monash Uni';
update jobs SET FK_customer_Id = '80' where cust_Name = 'Motec';
update jobs SET FK_customer_Id = '81' where cust_Name = 'Motor Sport';
update jobs SET FK_customer_Id = '82' where cust_Name = 'MSC Sales';
update jobs SET FK_customer_Id = '83' where cust_Name = 'MW Machinery';
update jobs SET FK_customer_Id = '84' where cust_Name = 'NDA Australia';
update jobs SET FK_customer_Id = '85' where cust_Name = 'Nova Tooling';
update jobs SET FK_customer_Id = '86' where cust_Name = 'Okuma Australia';
update jobs SET FK_customer_Id = '87' where cust_Name = 'Omega Plastics';
update jobs SET FK_customer_Id = '88' where cust_Name = 'Otto Designs';
update jobs SET FK_customer_Id = '89' where cust_Name = 'Palm Plastics';
update jobs SET FK_customer_Id = '90' where cust_Name = 'Pantomould';
update jobs SET FK_customer_Id = '91' where cust_Name = 'Paterson Fine Jewellery';
update jobs SET FK_customer_Id = '92' where cust_Name = 'Pentair Water';
update jobs SET FK_customer_Id = '93' where cust_Name = 'Perfect Tooling';
update jobs SET FK_customer_Id = '94' where cust_Name = 'Plastic Pipe Fabrications';
update jobs SET FK_customer_Id = '95' where cust_Name = 'Plastool';
update jobs SET FK_customer_Id = '96' where cust_Name = 'Preci Engg';
update jobs SET FK_customer_Id = '97' where cust_Name = 'Precitech';
update jobs SET FK_customer_Id = '98' where cust_Name = 'Primepak';
update jobs SET FK_customer_Id = '99' where cust_Name = 'Pryda';
update jobs SET FK_customer_Id = '100' where cust_Name = 'Ram Tooling';
update jobs SET FK_customer_Id = '101' where cust_Name = 'Red Backs Services';
update jobs SET FK_customer_Id = '102' where cust_Name = 'Renold';
update jobs SET FK_customer_Id = '103' where cust_Name = 'Rian Industries';
update jobs SET FK_customer_Id = '104' where cust_Name = 'Ritosi';
update jobs SET FK_customer_Id = '105' where cust_Name = 'Rohwedder';
update jobs SET FK_customer_Id = '106' where cust_Name = 'Ronstan';
update jobs SET FK_customer_Id = '107' where cust_Name = 'S.K.Engg.';
update jobs SET FK_customer_Id = '108' where cust_Name = 'Schinner Business Forms';
update jobs SET FK_customer_Id = '109' where cust_Name = 'Siemens Vdo';
update jobs SET FK_customer_Id = '111' where cust_Name = 'Silcraft';
update jobs SET FK_customer_Id = '112' where cust_Name = 'Sinclair Xray';
update jobs SET FK_customer_Id = '113' where cust_Name = 'Southern Grinding';
update jobs SET FK_customer_Id = '114' where cust_Name = 'Steelform Eng';
update jobs SET FK_customer_Id = '115' where cust_Name = 'Stug';
update jobs SET FK_customer_Id = '116' where cust_Name = 'Sumitomo';
update jobs SET FK_customer_Id = '117' where cust_Name = 'T & L Precision Engg.';
update jobs SET FK_customer_Id = '118' where cust_Name = 'Takas';
update jobs SET FK_customer_Id = '119' where cust_Name = 'Tarapath';
update jobs SET FK_customer_Id = '120' where cust_Name = 'Thompson Precision Eng';
update jobs SET FK_customer_Id = '121' where cust_Name = 'Trent CNC';
update jobs SET FK_customer_Id = '122' where cust_Name = 'Trico';
update jobs SET FK_customer_Id = '123' where cust_Name = 'Tulip';
update jobs SET FK_customer_Id = '124' where cust_Name = 'VDO';
update jobs SET FK_customer_Id = '125' where cust_Name = 'Venture Industries';
update jobs SET FK_customer_Id = '126' where cust_Name = 'Vicfam';
update jobs SET FK_customer_Id = '127' where cust_Name = 'Victoria University';
update jobs SET FK_customer_Id = '128' where cust_Name = 'Viscount';
update jobs SET FK_customer_Id = '129' where cust_Name = 'Vision Fire & Security';
update jobs SET FK_customer_Id = '130' where cust_Name = 'Wilex Plastics';

