# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anilet/python/atlas/ui/atlasMain.ui'
#
# Created: Sat Oct 11 23:47:40 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882,600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(4,4,861,471))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.dailyTab = QtGui.QWidget()
        self.dailyTab.setObjectName("dailyTab")
        self.widget = QtGui.QWidget(self.dailyTab)
        self.widget.setGeometry(QtCore.QRect(4,4,514,194))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.timeCalendar = QtGui.QCalendarWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeCalendar.sizePolicy().hasHeightForWidth())
        self.timeCalendar.setSizePolicy(sizePolicy)
        self.timeCalendar.setSizeIncrement(QtCore.QSize(0,0))
        self.timeCalendar.setGridVisible(True)
        self.timeCalendar.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.timeCalendar.setObjectName("timeCalendar")
        self.horizontalLayout_5.addWidget(self.timeCalendar)
        self.tableView = QtGui.QTableView(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setSizeIncrement(QtCore.QSize(2,0))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_5.addWidget(self.tableView)
        self.dailyTimeGP = QtGui.QGroupBox(self.dailyTab)
        self.dailyTimeGP.setGeometry(QtCore.QRect(6,258,261,110))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dailyTimeGP.sizePolicy().hasHeightForWidth())
        self.dailyTimeGP.setSizePolicy(sizePolicy)
        self.dailyTimeGP.setMinimumSize(QtCore.QSize(0,0))
        self.dailyTimeGP.setObjectName("dailyTimeGP")
        self.verticalLayout = QtGui.QVBoxLayout(self.dailyTimeGP)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.dailyTimeGP)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.inLineEdit = QtGui.QLineEdit(self.dailyTimeGP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inLineEdit.sizePolicy().hasHeightForWidth())
        self.inLineEdit.setSizePolicy(sizePolicy)
        self.inLineEdit.setMaxLength(5)
        self.inLineEdit.setObjectName("inLineEdit")
        self.horizontalLayout_3.addWidget(self.inLineEdit)
        self.inComboBox = QtGui.QComboBox(self.dailyTimeGP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inComboBox.sizePolicy().hasHeightForWidth())
        self.inComboBox.setSizePolicy(sizePolicy)
        self.inComboBox.setObjectName("inComboBox")
        self.horizontalLayout_3.addWidget(self.inComboBox)
        self.label_2 = QtGui.QLabel(self.dailyTimeGP)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.outLineEdit = QtGui.QLineEdit(self.dailyTimeGP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outLineEdit.sizePolicy().hasHeightForWidth())
        self.outLineEdit.setSizePolicy(sizePolicy)
        self.outLineEdit.setMaxLength(5)
        self.outLineEdit.setObjectName("outLineEdit")
        self.horizontalLayout_3.addWidget(self.outLineEdit)
        self.outComboBox = QtGui.QComboBox(self.dailyTimeGP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outComboBox.sizePolicy().hasHeightForWidth())
        self.outComboBox.setSizePolicy(sizePolicy)
        self.outComboBox.setObjectName("outComboBox")
        self.horizontalLayout_3.addWidget(self.outComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.totalHourdLabel = QtGui.QLabel(self.dailyTimeGP)
        self.totalHourdLabel.setObjectName("totalHourdLabel")
        self.horizontalLayout_4.addWidget(self.totalHourdLabel)
        spacerItem = QtGui.QSpacerItem(98,25,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.addDailyTimeButton = QtGui.QPushButton(self.dailyTimeGP)
        self.addDailyTimeButton.setObjectName("addDailyTimeButton")
        self.horizontalLayout_4.addWidget(self.addDailyTimeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget1 = QtGui.QWidget(self.dailyTab)
        self.widget1.setGeometry(QtCore.QRect(568,257,264,228))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hourTable = QtGui.QTableWidget(self.widget1)
        self.hourTable.setObjectName("hourTable")
        self.verticalLayout_3.addWidget(self.hourTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtGui.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtGui.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.mainTabWidget.addTab(self.dailyTab,"")
        self.historyTab = QtGui.QWidget()
        self.historyTab.setObjectName("historyTab")
        self.mainTabWidget.addTab(self.historyTab,"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,882,27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.dailyTimeGP.setTitle(QtGui.QApplication.translate("MainWindow", "Daily Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Time In:", None, QtGui.QApplication.UnicodeUTF8))
        self.inLineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter time in in the format 12:30", None, QtGui.QApplication.UnicodeUTF8))
        self.inComboBox.addItem(QtGui.QApplication.translate("MainWindow", "AM", None, QtGui.QApplication.UnicodeUTF8))
        self.inComboBox.addItem(QtGui.QApplication.translate("MainWindow", "PM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Time Out:", None, QtGui.QApplication.UnicodeUTF8))
        self.outLineEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter time in 12:30 format", None, QtGui.QApplication.UnicodeUTF8))
        self.outComboBox.addItem(QtGui.QApplication.translate("MainWindow", "PM", None, QtGui.QApplication.UnicodeUTF8))
        self.outComboBox.addItem(QtGui.QApplication.translate("MainWindow", "AM", None, QtGui.QApplication.UnicodeUTF8))
        self.totalHourdLabel.setText(QtGui.QApplication.translate("MainWindow", "Total Hours Worked", None, QtGui.QApplication.UnicodeUTF8))
        self.addDailyTimeButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.hourTable.clear()
        self.hourTable.setColumnCount(0)
        self.hourTable.setRowCount(0)
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.dailyTab), QtGui.QApplication.translate("MainWindow", "Daily Time", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.historyTab), QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))

