# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anilet/python/atlas/ui/databaseDlg.ui'
#
# Created: Sat Oct 11 23:47:39 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DatabaseDlg(object):
    def setupUi(self, DatabaseDlg):
        DatabaseDlg.setObjectName("DatabaseDlg")
        DatabaseDlg.resize(348,298)
        self.gridlayout = QtGui.QGridLayout(DatabaseDlg)
        self.gridlayout.setObjectName("gridlayout")
        self.textLabel6 = QtGui.QLabel(DatabaseDlg)
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridlayout.addWidget(self.textLabel6,0,2,1,1)
        self.textLabel1 = QtGui.QLabel(DatabaseDlg)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1,0,0,1,1)
        self.edHost = QtGui.QLineEdit(DatabaseDlg)
        self.edHost.setObjectName("edHost")
        self.gridlayout.addWidget(self.edHost,0,1,1,1)
        self.textLabel2 = QtGui.QLabel(DatabaseDlg)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridlayout.addWidget(self.textLabel2,1,0,1,1)
        self.edPass = QtGui.QLineEdit(DatabaseDlg)
        self.edPass.setEchoMode(QtGui.QLineEdit.Password)
        self.edPass.setObjectName("edPass")
        self.gridlayout.addWidget(self.edPass,3,1,1,3)
        self.textLabel3 = QtGui.QLabel(DatabaseDlg)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.gridlayout.addWidget(self.textLabel3,2,0,1,1)
        self.textLabel4 = QtGui.QLabel(DatabaseDlg)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridlayout.addWidget(self.textLabel4,3,0,1,1)
        self.edName = QtGui.QLineEdit(DatabaseDlg)
        self.edName.setObjectName("edName")
        self.gridlayout.addWidget(self.edName,1,1,1,3)
        self.edUser = QtGui.QLineEdit(DatabaseDlg)
        self.edUser.setObjectName("edUser")
        self.gridlayout.addWidget(self.edUser,2,1,1,3)
        self.edPort = QtGui.QSpinBox(DatabaseDlg)
        self.edPort.setMaximum(99999)
        self.edPort.setProperty("value",QtCore.QVariant(3306))
        self.edPort.setObjectName("edPort")
        self.gridlayout.addWidget(self.edPort,0,3,1,1)
        self.textLabel5 = QtGui.QLabel(DatabaseDlg)
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.gridlayout.addWidget(self.textLabel5,4,0,1,1)
        self.cbType = QtGui.QComboBox(DatabaseDlg)
        self.cbType.setObjectName("cbType")
        self.gridlayout.addWidget(self.cbType,4,1,1,3)
        spacerItem = QtGui.QSpacerItem(21,100,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem,7,1,1,1)
        spacerItem1 = QtGui.QSpacerItem(21,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1,5,1,1,1)
        self.btnTest = QtGui.QPushButton(DatabaseDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTest.sizePolicy().hasHeightForWidth())
        self.btnTest.setSizePolicy(sizePolicy)
        self.btnTest.setObjectName("btnTest")
        self.gridlayout.addWidget(self.btnTest,6,0,1,2)

        self.retranslateUi(DatabaseDlg)
        QtCore.QObject.connect(self.btnTest,QtCore.SIGNAL("clicked()"),DatabaseDlg.testConnectivity)
        QtCore.QMetaObject.connectSlotsByName(DatabaseDlg)
        DatabaseDlg.setTabOrder(self.edHost,self.edPort)
        DatabaseDlg.setTabOrder(self.edPort,self.edName)
        DatabaseDlg.setTabOrder(self.edName,self.edUser)
        DatabaseDlg.setTabOrder(self.edUser,self.edPass)
        DatabaseDlg.setTabOrder(self.edPass,self.cbType)
        DatabaseDlg.setTabOrder(self.cbType,self.btnTest)

    def retranslateUi(self, DatabaseDlg):
        DatabaseDlg.setWindowTitle(QtGui.QApplication.translate("DatabaseDlg", "Database Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel6.setText(QtGui.QApplication.translate("DatabaseDlg", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1.setText(QtGui.QApplication.translate("DatabaseDlg", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2.setText(QtGui.QApplication.translate("DatabaseDlg", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("DatabaseDlg", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("DatabaseDlg", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5.setText(QtGui.QApplication.translate("DatabaseDlg", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.addItem(QtGui.QApplication.translate("DatabaseDlg", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.cbType.addItem(QtGui.QApplication.translate("DatabaseDlg", "PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTest.setText(QtGui.QApplication.translate("DatabaseDlg", "Test connectivity", None, QtGui.QApplication.UnicodeUTF8))

