# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anilet/python/atlas/ui/jobWindow.ui'
#
# Created: Sun Oct 19 15:31:30 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtGui.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuJobs = QtGui.QMenu(self.menubar)
        self.menuJobs.setObjectName("menuJobs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAll_jobs = QtGui.QAction(MainWindow)
        self.actionAll_jobs.setObjectName("actionAll_jobs")
        self.actionCurrent_Jobs = QtGui.QAction(MainWindow)
        self.actionCurrent_Jobs.setObjectName("actionCurrent_Jobs")
        self.actionCompleted_Jobs = QtGui.QAction(MainWindow)
        self.actionCompleted_Jobs.setObjectName("actionCompleted_Jobs")
        self.actionSubcontract_Jobs = QtGui.QAction(MainWindow)
        self.actionSubcontract_Jobs.setObjectName("actionSubcontract_Jobs")
        self.menuExit.addAction(self.actionExit)
        self.menuJobs.addAction(self.actionAll_jobs)
        self.menuJobs.addAction(self.actionCurrent_Jobs)
        self.menuJobs.addAction(self.actionCompleted_Jobs)
        self.menuJobs.addSeparator()
        self.menuJobs.addAction(self.actionSubcontract_Jobs)
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuJobs.menuAction())
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.tableView)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Quick Search :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "type here to search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "All Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Current jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Completed Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Subcontracted Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExit.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuJobs.setTitle(QtGui.QApplication.translate("MainWindow", "jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAll_jobs.setText(QtGui.QApplication.translate("MainWindow", "All jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCurrent_Jobs.setText(QtGui.QApplication.translate("MainWindow", "Current Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleted_Jobs.setText(QtGui.QApplication.translate("MainWindow", "Completed Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSubcontract_Jobs.setText(QtGui.QApplication.translate("MainWindow", "subcontract Jobs", None, QtGui.QApplication.UnicodeUTF8))

