# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anilet/Bhima/python/atlas/ui/newjobDlg.ui'
#
# Created: Sun Nov 16 23:13:06 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_newjobDlg(object):
    def setupUi(self, newjobDlg):
        newjobDlg.setObjectName("newjobDlg")
        newjobDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        newjobDlg.resize(413, 475)
        self.verticalLayout_2 = QtGui.QVBoxLayout(newjobDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(newjobDlg)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.jobNoEdit = QtGui.QLineEdit(newjobDlg)
        self.jobNoEdit.setObjectName("jobNoEdit")
        self.gridLayout.addWidget(self.jobNoEdit, 0, 2, 1, 3)
        self.label_9 = QtGui.QLabel(newjobDlg)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 2)
        self.quoteNoEdit = QtGui.QLineEdit(newjobDlg)
        self.quoteNoEdit.setObjectName("quoteNoEdit")
        self.gridLayout.addWidget(self.quoteNoEdit, 1, 2, 1, 3)
        self.label_2 = QtGui.QLabel(newjobDlg)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.jobDescriptionEdit = QtGui.QLineEdit(newjobDlg)
        self.jobDescriptionEdit.setObjectName("jobDescriptionEdit")
        self.gridLayout.addWidget(self.jobDescriptionEdit, 2, 2, 1, 6)
        self.checkBox = QtGui.QCheckBox(newjobDlg)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 2, 1, 2)
        self.checkBox_2 = QtGui.QCheckBox(newjobDlg)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 3, 4, 1, 2)
        self.oldJobNoComboBox = QtGui.QComboBox(newjobDlg)
        self.oldJobNoComboBox.setObjectName("oldJobNoComboBox")
        self.gridLayout.addWidget(self.oldJobNoComboBox, 3, 6, 1, 2)
        self.jobTypeComboBox = QtGui.QComboBox(newjobDlg)
        self.jobTypeComboBox.setObjectName("jobTypeComboBox")
        self.gridLayout.addWidget(self.jobTypeComboBox, 4, 2, 1, 5)
        self.newJobTypeButton = QtGui.QToolButton(newjobDlg)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/16x16/actions/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newJobTypeButton.setIcon(icon)
        self.newJobTypeButton.setObjectName("newJobTypeButton")
        self.gridLayout.addWidget(self.newJobTypeButton, 4, 7, 1, 1)
        self.jobStatusComboBox = QtGui.QComboBox(newjobDlg)
        self.jobStatusComboBox.setObjectName("jobStatusComboBox")
        self.gridLayout.addWidget(self.jobStatusComboBox, 5, 2, 1, 5)
        self.newJobStatusButton = QtGui.QToolButton(newjobDlg)
        self.newJobStatusButton.setIcon(icon)
        self.newJobStatusButton.setObjectName("newJobStatusButton")
        self.gridLayout.addWidget(self.newJobStatusButton, 5, 7, 1, 1)
        self.partListButton = QtGui.QPushButton(newjobDlg)
        self.partListButton.setObjectName("partListButton")
        self.gridLayout.addWidget(self.partListButton, 6, 2, 1, 3)
        self.estdTimeButton = QtGui.QPushButton(newjobDlg)
        self.estdTimeButton.setObjectName("estdTimeButton")
        self.gridLayout.addWidget(self.estdTimeButton, 6, 5, 1, 3)
        self.startDate = QtGui.QDateEdit(newjobDlg)
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.gridLayout.addWidget(self.startDate, 7, 2, 1, 3)
        self.dueDate = QtGui.QDateEdit(newjobDlg)
        self.dueDate.setCalendarPopup(True)
        self.dueDate.setObjectName("dueDate")
        self.gridLayout.addWidget(self.dueDate, 8, 2, 1, 3)
        self.inchargeComboBox = QtGui.QComboBox(newjobDlg)
        self.inchargeComboBox.setObjectName("inchargeComboBox")
        self.gridLayout.addWidget(self.inchargeComboBox, 9, 2, 1, 5)
        self.newEmployeeButton = QtGui.QToolButton(newjobDlg)
        self.newEmployeeButton.setIcon(icon)
        self.newEmployeeButton.setObjectName("newEmployeeButton")
        self.gridLayout.addWidget(self.newEmployeeButton, 9, 7, 1, 1)
        self.remarksTextEdit = QtGui.QTextEdit(newjobDlg)
        self.remarksTextEdit.setObjectName("remarksTextEdit")
        self.gridLayout.addWidget(self.remarksTextEdit, 10, 2, 1, 6)
        self.customerComboBox = QtGui.QComboBox(newjobDlg)
        self.customerComboBox.setObjectName("customerComboBox")
        self.gridLayout.addWidget(self.customerComboBox, 11, 2, 1, 5)
        self.newCustomerButton = QtGui.QToolButton(newjobDlg)
        self.newCustomerButton.setIcon(icon)
        self.newCustomerButton.setObjectName("newCustomerButton")
        self.gridLayout.addWidget(self.newCustomerButton, 11, 7, 1, 1)
        self.label_4 = QtGui.QLabel(newjobDlg)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 12, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtGui.QLabel(newjobDlg)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        spacerItem = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 10, 1, 1, 1)
        self.label_3 = QtGui.QLabel(newjobDlg)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 1, 1, 1)
        self.label_10 = QtGui.QLabel(newjobDlg)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 1, 1, 1)
        self.label_6 = QtGui.QLabel(newjobDlg)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 1, 1, 1)
        self.label_5 = QtGui.QLabel(newjobDlg)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.label_7 = QtGui.QLabel(newjobDlg)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(newjobDlg)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.customerOrderLineEdit = QtGui.QLineEdit(newjobDlg)
        self.customerOrderLineEdit.setObjectName("customerOrderLineEdit")
        self.gridLayout.addWidget(self.customerOrderLineEdit, 12, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(newjobDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelButton = QtGui.QPushButton(newjobDlg)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.saveButton = QtGui.QPushButton(newjobDlg)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.jobNoEdit)
        self.label_9.setBuddy(self.quoteNoEdit)
        self.label_2.setBuddy(self.jobDescriptionEdit)
        self.label_4.setBuddy(self.customerOrderLineEdit)
        self.label_8.setBuddy(self.remarksTextEdit)
        self.label_3.setBuddy(self.customerComboBox)
        self.label_10.setBuddy(self.inchargeComboBox)
        self.label_6.setBuddy(self.dueDate)
        self.label_5.setBuddy(self.startDate)
        self.label_7.setBuddy(self.jobStatusComboBox)

        self.retranslateUi(newjobDlg)
        QtCore.QMetaObject.connectSlotsByName(newjobDlg)
        newjobDlg.setTabOrder(self.jobNoEdit, self.quoteNoEdit)
        newjobDlg.setTabOrder(self.quoteNoEdit, self.jobDescriptionEdit)
        newjobDlg.setTabOrder(self.jobDescriptionEdit, self.customerComboBox)
        newjobDlg.setTabOrder(self.customerComboBox, self.newCustomerButton)
        newjobDlg.setTabOrder(self.newCustomerButton, self.checkBox)
        newjobDlg.setTabOrder(self.checkBox, self.checkBox_2)
        newjobDlg.setTabOrder(self.checkBox_2, self.oldJobNoComboBox)
        newjobDlg.setTabOrder(self.oldJobNoComboBox, self.startDate)
        newjobDlg.setTabOrder(self.startDate, self.dueDate)
        newjobDlg.setTabOrder(self.dueDate, self.jobStatusComboBox)
        newjobDlg.setTabOrder(self.jobStatusComboBox, self.newJobStatusButton)
        newjobDlg.setTabOrder(self.newJobStatusButton, self.partListButton)
        newjobDlg.setTabOrder(self.partListButton, self.estdTimeButton)
        newjobDlg.setTabOrder(self.estdTimeButton, self.inchargeComboBox)
        newjobDlg.setTabOrder(self.inchargeComboBox, self.newEmployeeButton)
        newjobDlg.setTabOrder(self.newEmployeeButton, self.saveButton)
        newjobDlg.setTabOrder(self.saveButton, self.remarksTextEdit)
        newjobDlg.setTabOrder(self.remarksTextEdit, self.cancelButton)

    def retranslateUi(self, newjobDlg):
        newjobDlg.setWindowTitle(QtGui.QApplication.translate("newjobDlg", "New Job", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("newjobDlg", "Job No:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("newjobDlg", "Quote No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newjobDlg", "Job Description", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("newjobDlg", "Rework", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("newjobDlg", "Modification", None, QtGui.QApplication.UnicodeUTF8))
        self.newJobTypeButton.setToolTip(QtGui.QApplication.translate("newjobDlg", "New Job Type", None, QtGui.QApplication.UnicodeUTF8))
        self.newJobTypeButton.setStatusTip(QtGui.QApplication.translate("newjobDlg", "Create new Job type", None, QtGui.QApplication.UnicodeUTF8))
        self.newJobTypeButton.setText(QtGui.QApplication.translate("newjobDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.newJobStatusButton.setToolTip(QtGui.QApplication.translate("newjobDlg", "New Status", None, QtGui.QApplication.UnicodeUTF8))
        self.newJobStatusButton.setStatusTip(QtGui.QApplication.translate("newjobDlg", "Add a new Status", None, QtGui.QApplication.UnicodeUTF8))
        self.newJobStatusButton.setText(QtGui.QApplication.translate("newjobDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.partListButton.setText(QtGui.QApplication.translate("newjobDlg", "Part List", None, QtGui.QApplication.UnicodeUTF8))
        self.estdTimeButton.setText(QtGui.QApplication.translate("newjobDlg", "Estimated Time", None, QtGui.QApplication.UnicodeUTF8))
        self.newEmployeeButton.setToolTip(QtGui.QApplication.translate("newjobDlg", "New Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.newEmployeeButton.setStatusTip(QtGui.QApplication.translate("newjobDlg", "Add a new employee", None, QtGui.QApplication.UnicodeUTF8))
        self.newEmployeeButton.setText(QtGui.QApplication.translate("newjobDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.newCustomerButton.setToolTip(QtGui.QApplication.translate("newjobDlg", "New customer", None, QtGui.QApplication.UnicodeUTF8))
        self.newCustomerButton.setStatusTip(QtGui.QApplication.translate("newjobDlg", "Add a New customer", None, QtGui.QApplication.UnicodeUTF8))
        self.newCustomerButton.setText(QtGui.QApplication.translate("newjobDlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("newjobDlg", "Customer Order No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("newjobDlg", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("newjobDlg", "Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("newjobDlg", "In Charge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("newjobDlg", "Due Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("newjobDlg", "Start Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("newjobDlg", "Job Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("newjobDlg", "Job Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("newjobDlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("newjobDlg", "Save", None, QtGui.QApplication.UnicodeUTF8))

import smeTime_rc
