# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anilet/atlas/time-manage/ui/settingsDlg.ui'
#
# Created: Sun Nov 23 22:50:43 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_settingsDlg(object):
    def setupUi(self, settingsDlg):
        settingsDlg.setObjectName("settingsDlg")
        settingsDlg.resize(326, 370)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/16x16/actions/gtk-properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settingsDlg.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(settingsDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(settingsDlg)
        self.tabWidget.setObjectName("tabWidget")
        self.databaseTab = QtGui.QWidget()
        self.databaseTab.setObjectName("databaseTab")
        self.gridLayout = QtGui.QGridLayout(self.databaseTab)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.databaseTab)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.serverLineEdit = QtGui.QLineEdit(self.databaseTab)
        self.serverLineEdit.setObjectName("serverLineEdit")
        self.gridLayout.addWidget(self.serverLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.databaseTab)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.databaseLineEdit = QtGui.QLineEdit(self.databaseTab)
        self.databaseLineEdit.setObjectName("databaseLineEdit")
        self.gridLayout.addWidget(self.databaseLineEdit, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.databaseTab)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.portLineEdit = QtGui.QLineEdit(self.databaseTab)
        self.portLineEdit.setObjectName("portLineEdit")
        self.gridLayout.addWidget(self.portLineEdit, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.databaseTab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.userLineEdit = QtGui.QLineEdit(self.databaseTab)
        self.userLineEdit.setObjectName("userLineEdit")
        self.gridLayout.addWidget(self.userLineEdit, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.databaseTab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.databaseTab)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(146, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.testButton = QtGui.QPushButton(self.databaseTab)
        self.testButton.setObjectName("testButton")
        self.gridLayout.addWidget(self.testButton, 5, 1, 1, 1)
        self.tabWidget.addTab(self.databaseTab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtGui.QFrame(settingsDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelButton = QtGui.QPushButton(settingsDlg)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.saveButton = QtGui.QPushButton(settingsDlg)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.serverLineEdit)
        self.label_2.setBuddy(self.databaseLineEdit)
        self.label_5.setBuddy(self.portLineEdit)
        self.label_3.setBuddy(self.userLineEdit)
        self.label_4.setBuddy(self.passwordLineEdit)

        self.retranslateUi(settingsDlg)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), settingsDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(settingsDlg)
        settingsDlg.setTabOrder(self.serverLineEdit, self.databaseLineEdit)
        settingsDlg.setTabOrder(self.databaseLineEdit, self.portLineEdit)
        settingsDlg.setTabOrder(self.portLineEdit, self.userLineEdit)
        settingsDlg.setTabOrder(self.userLineEdit, self.passwordLineEdit)
        settingsDlg.setTabOrder(self.passwordLineEdit, self.testButton)
        settingsDlg.setTabOrder(self.testButton, self.saveButton)
        settingsDlg.setTabOrder(self.saveButton, self.cancelButton)
        settingsDlg.setTabOrder(self.cancelButton, self.tabWidget)

    def retranslateUi(self, settingsDlg):
        settingsDlg.setWindowTitle(QtGui.QApplication.translate("settingsDlg", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("settingsDlg", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settingsDlg", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("settingsDlg", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portLineEdit.setText(QtGui.QApplication.translate("settingsDlg", "3306", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("settingsDlg", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("settingsDlg", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.testButton.setText(QtGui.QApplication.translate("settingsDlg", "Test Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.databaseTab), QtGui.QApplication.translate("settingsDlg", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("settingsDlg", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("settingsDlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("settingsDlg", "Save", None, QtGui.QApplication.UnicodeUTF8))

import smeTime_rc
