# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anilet/python/atlas/ui/time.ui'
#
# Created: Sat Oct 11 23:47:40 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_atlasTimeDlg(object):
    def setupUi(self, atlasTimeDlg):
        atlasTimeDlg.setObjectName("atlasTimeDlg")
        atlasTimeDlg.resize(827,562)
        self.verticalLayout_3 = QtGui.QVBoxLayout(atlasTimeDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headLabel = QtGui.QLabel(atlasTimeDlg)
        self.headLabel.setObjectName("headLabel")
        self.verticalLayout_3.addWidget(self.headLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeCalendar = QtGui.QCalendarWidget(atlasTimeDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeCalendar.sizePolicy().hasHeightForWidth())
        self.timeCalendar.setSizePolicy(sizePolicy)
        self.timeCalendar.setGridVisible(True)
        self.timeCalendar.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.timeCalendar.setObjectName("timeCalendar")
        self.verticalLayout.addWidget(self.timeCalendar)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(atlasTimeDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2,0,0,1,2)
        self.label_3 = QtGui.QLabel(atlasTimeDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3,1,0,1,1)
        self.dayLable = QtGui.QLabel(atlasTimeDlg)
        self.dayLable.setObjectName("dayLable")
        self.gridLayout.addWidget(self.dayLable,1,1,1,1)
        self.label_4 = QtGui.QLabel(atlasTimeDlg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4,2,0,1,1)
        self.weekLabel = QtGui.QLabel(atlasTimeDlg)
        self.weekLabel.setObjectName("weekLabel")
        self.gridLayout.addWidget(self.weekLabel,2,1,1,1)
        self.label_5 = QtGui.QLabel(atlasTimeDlg)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5,3,0,1,1)
        self.monthLabel = QtGui.QLabel(atlasTimeDlg)
        self.monthLabel.setObjectName("monthLabel")
        self.gridLayout.addWidget(self.monthLabel,3,1,1,1)
        self.label_7 = QtGui.QLabel(atlasTimeDlg)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7,4,0,1,1)
        self.yearLabel = QtGui.QLabel(atlasTimeDlg)
        self.yearLabel.setObjectName("yearLabel")
        self.gridLayout.addWidget(self.yearLabel,4,1,1,1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.helpTextBrowser = QtGui.QTextBrowser(atlasTimeDlg)
        self.helpTextBrowser.setFrameShape(QtGui.QFrame.Box)
        self.helpTextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.helpTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.helpTextBrowser.setObjectName("helpTextBrowser")
        self.verticalLayout.addWidget(self.helpTextBrowser)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hourTable = QtGui.QTableWidget(atlasTimeDlg)
        self.hourTable.setObjectName("hourTable")
        self.verticalLayout_2.addWidget(self.hourTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtGui.QPushButton(atlasTimeDlg)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtGui.QPushButton(atlasTimeDlg)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(atlasTimeDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(648,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(atlasTimeDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(atlasTimeDlg)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),atlasTimeDlg.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),atlasTimeDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(atlasTimeDlg)

    def retranslateUi(self, atlasTimeDlg):
        atlasTimeDlg.setWindowTitle(QtGui.QApplication.translate("atlasTimeDlg", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.headLabel.setText(QtGui.QApplication.translate("atlasTimeDlg", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("atlasTimeDlg", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("atlasTimeDlg", "Total Hours for Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.dayLable.setText(QtGui.QApplication.translate("atlasTimeDlg", "day", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("atlasTimeDlg", "Total Hours for the Week", None, QtGui.QApplication.UnicodeUTF8))
        self.weekLabel.setText(QtGui.QApplication.translate("atlasTimeDlg", "week", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("atlasTimeDlg", "Total Hours for the Month", None, QtGui.QApplication.UnicodeUTF8))
        self.monthLabel.setText(QtGui.QApplication.translate("atlasTimeDlg", "month", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("atlasTimeDlg", "Total hours for the year:", None, QtGui.QApplication.UnicodeUTF8))
        self.yearLabel.setText(QtGui.QApplication.translate("atlasTimeDlg", "year", None, QtGui.QApplication.UnicodeUTF8))
        self.helpTextBrowser.setHtml(QtGui.QApplication.translate("atlasTimeDlg", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please select a date from the calendar to see the hours worked</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#0000ff;\">Doubble click</span> on a date to edit/enter worked hours</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.hourTable.clear()
        self.hourTable.setColumnCount(0)
        self.hourTable.setRowCount(0)
        self.pushButton.setText(QtGui.QApplication.translate("atlasTimeDlg", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("atlasTimeDlg", "PushButton", None, QtGui.QApplication.UnicodeUTF8))

